---
version: "3"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /home/snow/calibre/config:/home/snow/calibre/config
      - /home/snow/Windows-Share:/home/snow/calibre/books
    ports:
      - 8083:8083
    restart: unless-stopped
