kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-cluster-user-administrator
  namespace: default
roleRef:
  kind: ClusterRole
  name: psp:vmware-system-privileged                            #Default ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: sso:administrator@vsphere.snowlab.tech          #sso<username>@<domain>
  apiGroup: rbac.authorization.k8s.io
