apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsan-kube
  resources:
    requests:
        storage: 3Gi
           
