apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkgs-cl01
  namespace: production
spec:
  topology:
    controlPlane:
      count: 1
      class: best-effort-xsmall
      storageClass: tanzu-default
    workers:
      count: 3
      class: best-effort-small
      storageClass: tanzu-default
  distribution:
    version: v1.20
  settings:
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks: ["172.16.0.0/16"]
      services:
        cidrBlocks: ["172.17.0.0/16"]
      serviceDomain: "cluster.local"
    storage:
      defaultClass: tanzu-default
