kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tkgs-clusterrole
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  - get
  - create
  - patch
  - update
  - list
  - watch
  - delete
  resourceNames:
  - kubeapps-psp
