#@data/values
#@overlay/match-child-defaults missing_ok=True
---
logging:
  image:
    repository: projects.registry.vmware.com/tkg
tkg:
  instance_name: "production"
  cluster_name: "tkgs-cl01"
fluent_bit:
  output_plugin: "syslog"
  syslog:
    host: "vrli.corp.snowlab.tech"
    port: "514"
    mode: "tcp"
    format: "rfc5424"
