apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tkgs-clusterrole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tkgs-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccount
- kind: Group
  name: system:nodes
- kind: ServiceAccount # Omit apiGroup
  name: default
